/* Autogenerated by png2wx.pl on Mon Sep 14 21:59:46 2009 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_colscheme;
extern wxBitmap *_img_current;
extern wxBitmap *_img_down;
extern wxBitmap *_img_exitt;
extern wxBitmap *_img_follow;
extern wxBitmap *_img_gpx_export;
extern wxBitmap *_img_gpx_import;
extern wxBitmap *_img_help;
extern wxBitmap *_img_left;
extern wxBitmap *_img_mob;
extern wxBitmap *_img_opencpn;
extern wxBitmap *_img_pencil;
extern wxBitmap *_img_print;
extern wxBitmap *_img_right;
extern wxBitmap *_img_route;
extern wxBitmap *_img_scin;
extern wxBitmap *_img_scout;
extern wxBitmap *_img_settings;
extern wxBitmap *_img_ship_green;
extern wxBitmap *_img_ship_red;
extern wxBitmap *_img_text;
extern wxBitmap *_img_tide;
extern wxBitmap *_img_tidesml;
extern wxBitmap *_img_track;
extern wxBitmap *_img_up;
extern wxBitmap *_img_zoomin;
extern wxBitmap *_img_zoomout;

#endif /* ICONS_H */
